### ISSUE TITLE
Dump .dropbox file

### ISSUE THREAD

**Issue by jakirkham** [bnhwa/datapak#1]
This can be done by running `git rm .dropbox` and then `git commit`.

**Comment by jakirkham** [comment]
Maybe the same story with the `Icon` file.

**Comment by bnhwa** [comment]
did it

**Comment by bnhwa** [comment]
should i close the issue after i fix the issue?

**Comment by jakirkham** [comment]
Yep, that's fine. You can also add text to the commit message so it will close the issue for you (e.g. writing a message like "Removed Icon .dropbox file. Fixes #1"). Once the commit is pushed to `master`, it will close out the issue for you. This way you can go back and see what you did. More info here ( https://help.github.com/articles/closing-issues-via-commit-messages/ )
